### ISSUE TITLE
[Bug] Node versions are not aligned across Docker and runtime

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#307]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

## Describe the bug
The Node version the project uses is inconsistent. Also, Node v16 is no longer supported.

[Node.js Previous Releases](https://nodejs.org/en/about/previous-releases)

![Node.js graph of release timelines](https://nodejs.org/_next/image?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnodejs%2FRelease%2Fmain%2Fschedule.svg%3Fsanitize%3Dtrue&w=3840&q=75&dpl=dpl_GdMsPAUhvpLTJnMxH5XZE3XPoKLh)

```bash
# Dockerfile
Node: v16.20.2

# GitHub checks workflow
Node: v18.16.0

# nvmrc
Node: v16
```

## Expected behavior
All Node versions should be consistent.

## Tasks

- [ ] Update Node version in GitHub Actions
- [ ] Update Node version in `Dockerfile`
- [ ] Update Node version in `package.json`
- [ ] Update Node version in `.nvmrc`
- [ ] Add new file `.node-version` file

**Comment by kmcginnes** [comment]
Related to #303, #305, #306

**Comment by kmcginnes** [comment]
Also, GitHub Actions is unhappy about our Node version choices:

<img width="959" alt="Screenshot 2024-04-24 at 3 42 40 PM" src="https://github.com/aws/graph-explorer/assets/212862/c1e8cb5d-e041-4ec7-bed6-633a5199082b">
