### ISSUE TITLE
Update GitHub issue templates

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#323]
## Description

The current issue structure can be vastly improved with some simple enhancements to the formatting and wording.

Today, issue submitters are leaving what were designed to be comments to the author in the description of the issue.

We should instead provide those notes to the author in HTML comments within the Markdown so that they won't be rendered.

## Tasks

- [ ] Issues -- bug template
- [ ] Issues -- feature request template
- [ ] Issues -- security vulnerability template

**Comment by kmcginnes** [comment]
I've been using this recently for my feature requests, and I like the way it reads:

```markdown
## Description
Provide a description of the enhancement you would like to see included in Graph Explorer

## Related Issues
Relates to issue #xxx.

## Tasks
- [ ] Add any known subtasks

---

> [!IMPORTANT]
> If you are interested in working on this issue or have submitted a pull request, please leave a comment.

> [!TIP]
> Please use a 👍 reaction to provide a +1/vote. 
> 
> This helps the community and maintainers prioritize this request.

```
