### ISSUE TITLE
[Task] Allow Prettier and ESLint to cover everything

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#327]
## Description
Allow Prettier and ESLint to check as much code as possible.

## Additional Context
We are currently ignoring:

- All Markdown files
- All files in the documentation folder
- The entire proxy server folder
- The `/.github/` folder

## Related Issues

Originally part of #303.

## Tasks
- [ ] Let Prettier update format of server code and config files
- [ ] Fix ESLint errors in server
- [ ] Fix tsconfig issue

---

> [!IMPORTANT]
> If you are interested in working on this issue or have submitted a pull request, please leave a comment.

> [!TIP]
> Please use a 👍 reaction to provide a +1/vote. 
> 
> This helps the community and maintainers prioritize this request.
