### ISSUE TITLE
Wrap `fetchSchema` in React Query

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#336]
## Related Issues
- Parent #304 

## Tasks
- [x] Handle loading state
- [x] Handle error state
- [x] Ensure cache policy is appropriate for the data
- [x] Ensure retry policy is appropriate
