### ISSUE TITLE
[Task] Wrap `fetchVertexCountsByType` in React Query

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#337]
## Tasks
- [ ] Handle loading state
- [ ] Handle error state
- [ ] Ensure cache policy is appropriate for the data
- [ ] Ensure retry policy is appropriate
