### ISSUE TITLE
[Task] Wrap `fetchNeighborsCount` in React Query

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#339]
## Tasks
- [x] Handle loading state
- [x] Handle error state
- [x] Ensure cache policy is appropriate for the data
- [x] Ensure retry policy is appropriate
