### ISSUE TITLE
[Task] Wrap `keywordSearch` in React Query

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#340]
## Tasks
- [x] Consolidate search in `DataExplorer` and `KeywordSearch`
- [ ] Handle loading state
- [ ] Handle error state
- [ ] Ensure cache policy is appropriate for the data
- [ ] Ensure retry policy is appropriate
