### ISSUE TITLE
[Task] Defer neighbor counts by type query for the expand side bar

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#341]
When adding a node to the graph, we fire off a query to get the neighbor node types and counts to show in the side bar and in the graph.

This is can be an expensive query that is not handled well by the UI. If it fails nothing happens, if it is slow nothing happens.

## Notes

This query is performed in two places.
- Adding a node to the graph
- Expanding the neighbors of a node

## Tasks

- [x] Add feedback in the side bar while the data loads
- [x] Hide the count of neighbors in the node on the graph until the data is retrieved
- [x] Add an error message and a retry button in the side bar if it fails

## Related Issues
- Parent #369 
- #263
- #269 
- #314

**Comment by kmcginnes** [comment]
This was completed a while ago
