### ISSUE TITLE
Node and edge details should load lazily

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#351]
When selecting a node or edge, the sidebar should show the most up to date information or the user should have the option of refreshing the information.

## Implementation
There are two places that node/edge details are shown: search and sidebar.

Each of those should be updated to get the details when the node or edge is selected. 

This means that the search queries should either be simplified to not return the properties of the result items, or the search query proactively updates the cache of each result item's properties query.

## Tasks
- [ ] Use React Query to manage node details
- [ ] Use React Query to manage edge details
- [ ] Update search query to not return node details
- [ ] Update expand neighbors query to not return node details
- [ ] Add button to refresh details in sidebar
- [ ] Add error UI with retry button for failures
