### ISSUE TITLE
[Project] Neighbor expansion UX

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#457]
Placeholder project for rethinking the experience of neighbor expansion through Graph Explorer.

## Current Implementation

- Sidebar UI is confusing
- Filter options are hidden by default making them difficult to discover
- Limit behavior can be inconsistent depending on the state of the graph

## Tasks
- [ ] [Spike] Gather goals for neighbor expansion
- [ ] [Spike] Rough UI designs to achieve goals
- [ ] [Spike] Plan implementation
