### ISSUE TITLE
[Project] Better integration of client and server

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#504]
The client React code is hosted by the proxy server by default. This means they are already linked together. We can more tightly integrate these two sides making configuration simpler, client side logic simpler, and the user experience better.

## Default Connection Configuration

Currently, the default connection is configured in a myriad of ways.

- Environment values set at docker run time
- Environment values set in `.env` file
- A `config.json` file that sets environment values

Then a Bash script interprets all of these options and generates a `defaultConnection.json` file. That file is then served as a static file by the `/defaultConnection` endpoint in Express.

Instead, I propose simplifying the approach a bit. The `/defaultConnection` endpoint can read the environment values, validate them, and generate the proper JSON object to send to the client. This removes complex and brittle Bash code to parse and manipulate JSON files and provides an easier path to testing the logic.

## Remove config.json option

This is a simplification of the ways to configure Graph Explorer. Environment values provide plenty of convenience for most situations. Having a config file as an additional path to setting environment values adds a new path that must be kept in sync and tested along with the straight environment value path.

If removing `config.json` as an option is not possible, we should at least move the Bash script logic into the Express server JavaScript code, since we are manipulating JSON objects. This will make testing and validation much easier to accomplish, and removes another step from the Docker startup process.

## Tasks

- [ ] [Task] Move default config generation in to server endpoint 
- [ ] [Task] Remove `config.json` as an option
- [ ] [Task] Add `vite-express` and combine client and server

**Comment by disfluxly** [comment]
Definitely in favor of this, and perhaps 1 suggestion would be the ability for the synchronizations to be executed on an interval by the backend server & then cached

**Comment by kmcginnes** [comment]
@disfluxly We are considering different options for the schema sync process that might alleviate some of the issues you and other users have seen.

- #1051
- #160 
- #1052

One concern for caching the schema server side would be security. The schema may contain customer data that is sensitive and would need to be properly protected. That adds effort and complexity.

If we allow easy sharing and hand modifying the schema through a file then the potentially sensitive user data is always in the user's control.

**Comment by kmcginnes** [comment]
That is all certainly possible. We will see how it shapes up.

So far we have avoided needing any sort of user management, login, or permissions by keeping all Graph Explorer data local to the user. But I'm sure at some point they will need to sneak in just to enable more functionality.
