### ISSUE TITLE
[Feature Request] Use RDF namespaces across the app

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#589]
## Description

When using RDF in Graph Explorer, it would be useful if the namespaces are used across the app in all labels.

This will make the labels shorter and less likely to wrap to a new line.

## Preferred Solution

- Use namespaces consistently for class labels
- Use namespaces for resource URIs

## Related Issues

None

## Tasks

- [x] [Task] Use namespace in search results list
- [x] [Task] Use namespace for resource URI
- [x] [Task] Use namespace for node labels
- [ ] [Task] Use namespace for node & edge style list
- [x] [Task] Use namespace for column headers in Data Explorer

---

> [!IMPORTANT]
> If you are interested in working on this issue or have submitted
> a pull request, please leave a comment.

> [!TIP]
> Please use a 👍 reaction to provide a +1/vote.
>
> This helps the community and maintainers prioritize this request.

**Comment by kmcginnes** [comment]
Data explorer should use the shorter namespaces for the column headers. We could put the full URI in a tooltip.

![CleanShot 2024-10-31 at 11 06 57@2x](https://github.com/user-attachments/assets/9204fb66-26ea-4d71-927e-a7df93badff3)

**Comment by kmcginnes** [comment]
Other places it would be useful:

## Node details
<img src="https://github.com/user-attachments/assets/1043dd60-cf12-4634-850d-406c14a6d492" alt="Node details screenshot" width="300px" style="max-width: 100%;">

## Search placeholder text
<img src="https://github.com/user-attachments/assets/33a76c6e-4250-4e5f-afe6-98c2a3dfc216" alt="Search placeholder text screenshot" width="600px" style="max-width: 100%;">

## Search details
<img src="https://github.com/user-attachments/assets/67b7d275-1b9e-4595-b47d-9bd4cb7aebfa" alt="Search details screenshot" width="600px" style="max-width: 100%;">

**Comment by kmcginnes** [comment]
This was fixed at some point. The list of styles should continue to render the full URI.
