### ISSUE TITLE
[Project] Handle thousands of node or edge types (Part 2)

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#601]
Improve performance for databases with large amounts of node or edge types (over 1,000).

## Issue

The UI can be quite sluggish. There are multiple places in the UI that list out all the node or edge types.

- Keyword search "Node Type" drop down
- Filter side bar panel
- Node styles side bar panel
- Edge styles side bar panel
- Connection detail data explorer node type list

## Related issues

- Part 1 #588

## Tasks

- [ ] [Task] Add paging to node styles side bar panel
- [ ] [Task] Add paging to edge styles side bar panel
- [ ] [Task] Reconsider filters panel
- [ ] [Task] Reconsider node type drop down in search

**Comment by kmcginnes** [comment]
The following issue covered similar ground:

- https://github.com/aws/graph-explorer/issues/886

Now Graph Explorer uses virtualization in the node styles, edge styles, and filters sidebar panels. In addition, the filters sidebar panel was split in to separate node and edge tabs.
