### ISSUE TITLE
[Spike] Proof of concept for Next.js

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#623]
Provide a proof of concept for Next.js working as a replacement for the proxy server.

Evaluate how long a fully functional migration might take.

## Tasks

- [x] Add Next.js dependencies
- [x] Get app to render
- [x] Move logger to Next.js route
- [x] Move gremlin requests to Next.js route

**Comment by kmcginnes** [comment]
I have a working branch with all Gremlin requests going through a Next.js route handler. 

The last step would be to get it working on Neptune Notebook, but I'm going to hold off on that for a little bit.
