### ISSUE TITLE
Prepare release 1.11.0

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#653]
## Tasks

- [x] Update change log
- [x] Bump versions
- [x] Test in Notebook
- [x] Create release branch
- [x] Create release in GitHub
