### ISSUE TITLE
[Task] Finalize search sidebar UI

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#659]
Make the prototype of search in the sidebar production ready.

## Tasks

- [ ] Create new branch with prototype code related to new search UI
- [ ] Test in all query languages
- [ ] Add paging
  - #106  
- [ ] Finalize new components
