### ISSUE TITLE
[Project] Use Tailwind

### ISSUE THREAD

**Issue by kmcginnes** [aws/graph-explorer#700]
Migrate the app over to using Tailwind as the primary CSS styling method.

This is being done incrementally. Some minor design tweaks help to modernize the app while the transition is being made.

## Tasks

- [x] [Task] Install Tailwind
- [x] [Task] Implement current Graph Explorer theme inside Tailwind config
- [x] [Task] Migrate ModuleContainer to Radix & Tailwind
- [x] [Task] Migrate Checkbox to Radix & Tailwind
- [ ] [Task] Migrate Modal to Radix & Tailwind
- [ ] [Task] Migrate Button to Radix & Tailwind
- [ ] [Task] Migrate FileUpload to Radix & Tailwind
- [ ] [Task] Migrate AdvancedList to Tailwind
- [ ] [Task] Migrate toast notifications to Sonner & Tailwind
- [ ] [Task] Migrate Select to Radix & Tailwind
- [ ] [Task] Migrate Input to Radix & Tailwind
- [ ] [Task] Migrate Tooltip to Radix & Tailwind
- [ ] [Task] Migrate ColorInput to Radix & Tailwind
- [ ] [Task] Remove Mantine
- [ ] [Task] Remove react-laag
- [ ] [Task] Remove useLayer()
- [ ] [Task] Remove EmotionCSS
